### ISSUE TITLE
File not found when run with java

### ISSUE THREAD

**Issue by maxliu007** [smallstep/autocert#17] opened 2020-11-11 11:22 UTC
Cannot locate the file when start up java gRPC server with Spring Boot. I can list the 3 files if my app not using them which run smoothly that I can get into the container to list those 3 files.
 Here is the deployment yml:
![image](https://user-images.githubusercontent.com/54350267/98805613-d38bba00-2452-11eb-8b2d-86f5e7dc491e.png)

![image](https://user-images.githubusercontent.com/54350267/98805692-ed2d0180-2452-11eb-93f2-f0240841d498.png)

![image](https://user-images.githubusercontent.com/54350267/98805554-b820af00-2452-11eb-9a3c-ae3c24bbed80.png)

**Comment by maraino** [comment] 2020-11-11 23:18
Is autocert enabled in the namespace? See https://github.com/smallstep/autocert#enable-autocert-per-namespace

Do you have an autocert sidecar container? Can you exec in it and see if the certs are in `/var/run/autocert.step.sm`

**Comment by maxliu007** [comment] 2020-11-12 09:45
Just verified, it was due to the Spring Framework 's Resource class. "file:" prefix is required to prepend to the file path.
e.g. /var/run/autocert.step.sm/root.crt -> "file:/var/run/autocert.step.sm/root.crt". It works now. 
**It is NOT an autocert issue or bug.**

I am using Java gGPRC server backed by Netty, we cannot use the "site.key" directly without the conversion :
openssl pkcs8 -topk8 -inform pem -in site.key -outform pem -nocrypt -out site.key.pem
It is not that convenient however.

**Comment by maraino** [comment] 2020-11-12 18:51
@maxliu007 The problem is that the same is true the other way around. Something that we can do is add options to save the file using PKCS#8

You can also use just `step` for that:
```sh
step crypto key format --pkcs8 --pem --no-password --insecure --out site.key.pem site.key
```

**Comment by maraino** [comment] 2020-11-12 19:14
I'm going to close this issue as I already created issues in `step` and autocert to support `PKCS  #8`
https://github.com/smallstep/cli/issues/387
https://github.com/smallstep/autocert/issues/18

**Closed by maraino** 2020-11-12 19:14 UTC
Labels: bug, needs triage
